name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          # Issues config
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-issue-message: 'This issue has been automatically closed due to inactivity. Please feel free to reopen it if you believe it still needs attention.'

          # Pull request config
          stale-pr-message: 'This PR has been automatically marked as stale because it has had no recent activity. It will be closed if no further activity occurs.'
          close-pr-message: 'This PR was closed because it has been inactive for 1 day since being marked as stale.'
          days-before-pr-stale: 2
          days-before-pr-close: 1

          # Labels
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'

          # Exempt labels
          exempt-issue-labels: 'pinned,security,help wanted,good first issue,bug'
          exempt-pr-labels: 'pinned,security,work in progress'

          # Additional settings
          exempt-all-milestones: true  # Don't mark issues/PRs with milestones as stale
          operations-per-run: 100  # Limit operations per run to avoid hitting API limits
          remove-stale-when-updated: true  # Remove stale label when updated
