name: Trigger Size Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'vite.config.ts'
      - 'bun.lockb'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build with stats
        run: |
          VITE_BUNDLE_ANALYZE=true bun run build --mode production

      - name: Save stats as artifact                                                                                      
        if: success()                                                                                                     
        uses: actions/upload-artifact@v3                                                                                  
        with:                                                                                                             
          name: bundle-stats                                                                                              
          path: dist/stats.html                                                                                           

      - name: Extract stats                                                                                               
        id: stats-extract                                                                                                 
        if: success()                                                                                                     
        run: |                                                                                                            
          if [ -f dist/stats.html ]; then                                                                                 
            echo "stats<<EOF" >> $GITHUB_OUTPUT                                                                           
            echo "## 📦 Bundle Size Analysis" >> $GITHUB_OUTPUT                                                           
            echo "" >> $GITHUB_OUTPUT                                                                                     
                                                                                                                          
            # Extract total bundle size                                                                                   
            TOTAL_SIZE=$(cat dist/stats.html | grep -o '"renderedLength":[0-9]*' | sed 's/"renderedLength"://' | awk '{ s += $1 } END { print sum/1024/1024 }')                                                                                     
            echo "Total Bundle Size: **${TOTAL_SIZE:.1f} MB**" >> $GITHUB_OUTPUT                                          
            echo "" >> $GITHUB_OUTPUT                                                                                     
                                                                                                                          
            echo "### Top Dependencies" >> $GITHUB_OUTPUT                                                                 
            echo "\`\`\`" >> $GITHUB_OUTPUT                                                                               
                                                                                                                          
            # Extract dependency sizes (looking for node_modules entries)                                                 
            cat dist/stats.html | grep -o '"name":"[^"]*","renderedLength":[0-9]*' | grep "node_modules" | sed 's/"name":"//' | sed 's/","renderedLength":/\t/' | while read -r DEP SIZE; do                                             
              if [ $SIZE -gt 5120 ]; then  # Only show deps > 5KB                                                         
                KB_SIZE=$((SIZE/1024))                                                                                    
                DEP_NAME=$(echo $DEP | sed 's/.*node_modules\///' | cut -d'/' -f1)                                        
                printf "%-20s %6d KB\n" "$DEP_NAME" "$KB_SIZE"                                                            
              fi                                                                                                          
            done | sort -k2 -nr | head -n 10 >> $GITHUB_OUTPUT                                                            
                                                                                                                          
            echo "\`\`\`" >> $GITHUB_OUTPUT                                                                               
            echo "EOF" >> $GITHUB_OUTPUT                                                                                  
          else                                                                                                            
            echo "Stats file not found at dist/stats.html"                                                                
            exit 1                                                                                                        
          fi                                                                                                              
                                                                                                                          
      - name: Read and post stats                                                                                         
        if: success()                                                                                                     
        uses: mshick/add-pr-comment@v2                                                                                    
        with:                                                                                                             
          message: |                                                                                                      
            ${{ steps.stats-extract.outputs.stats }}                                                                      
                                                                                                                          
            <details>                                                                                                     
            <summary>ℹ️ About this report</summary>                                                                       
            - Shows the total bundle size and top dependencies by size                                                    
            - Only dependencies larger than 5KB are listed                                                                
            - Sizes are shown in kilobytes (KB)                                                                           
            </details>                                                                                                    
          proxy-url: https://add-pr-comment-proxy-tscircuit.vercel.app/api                                                
          repo-token: ${{ secrets.GITHUB_TOKEN }}                                                                         
          allow-repeats: false                                                                                            

                                                                                                                          
      - name: Read and post stats                                                                                         
        if: success()                                                                                                     
        uses: mshick/add-pr-comment@v2                                                                                    
        with:                                                                                                             
          message: |                                                                                                      
            ## 📊 Bundle Size Analysis                                                                                    
                                                                                                                          
            ```                                                                                                           
            ${{ steps.stats-extract.outputs.stats }}                                                                      
            ```                                                                                                           
                                                                                                                          
            <details>                                                                                                     
            <summary>What is this?</summary>                                                                              
            This is an automated bundle size report generated during the build process. It shows the size of each chunk in the bundle.                                                                                                               
            </details>                                                                                                    
          proxy-url: https://add-pr-comment-proxy-tscircuit.vercel.app/api                                                
          repo-token: ${{ secrets.GITHUB_TOKEN }}                                                                         
          allow-repeats: false                                                                                            
 
