name: Trigger Size Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'vite.config.ts'
      - 'bun.lockb'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build with stats
        run: |
          VITE_BUNDLE_ANALYZE=true bun run build --mode production

      - name: Save stats as artifact                                                                                      
        if: success()                                                                                                     
        uses: actions/upload-artifact@v3                                                                                  
        with:                                                                                                             
          name: bundle-stats                                                                                              
          path: dist/stats.html                                                                                           

      - name: Extract stats                                                                                               
        id: stats-extract                                                                                                 
        if: success()                                                                                                     
        run: |                                                                                                            
          if [ -f dist/stats.html ]; then                                                                                 
            # Debug total size calculation                                                                                
            echo "Calculating total size..."                                                                              
            SIZES=$(cat dist/stats.html | grep -o '"renderedLength":[0-9]*' | sed 's/"renderedLength"://')                
            TOTAL_BYTES=$(echo "$SIZES" | awk '{ sum += $1 } END { print sum }')                                          
            TOTAL_MB=$(echo "scale=1; $TOTAL_BYTES/1024/1024" | bc)                                                       
            echo "Total MB: $TOTAL_MB"                                                                                    
                                                                                                                          
            echo "Finding node_modules entries..."                                                                        
            # Debug: Show what we're finding                                                                              
            echo "Sample of raw data:"                                                                                    
            cat dist/stats.html | grep -A2 '"nodeParts"' | head -n 10                                                     
                                                                                                                          
            # Store the node modules data in a temporary file                                                             
            cat dist/stats.html | grep -o '"id":"[^"]*node_modules[^"]*","renderedLength":[0-9]*' > temp_modules.txt
                                                                                                                          
            echo "Contents of temp_modules.txt:"                                                                          
            head -n 10 temp_modules.txt                                                                                   
                                                                                                                          
            {                                                                                                             
              echo "stats<<EOF"                                                                                           
              echo "## 📦 Bundle Size Analysis"                                                                           
              echo ""                                                                                                     
              echo "Total Bundle Size: **${TOTAL_MB} MB**"                                                                
              echo ""                                                                                                     
              echo "### Top Dependencies"                                                                                 
              echo "\`\`\`"                                                                                               
                                                                                                                          
              # Process dependencies with debugging                                                                       
              echo "Processing dependencies..."                                                                           
              while IFS= read -r line || [ -n "$line" ]; do                                                                             
                if [[ $line == *"node_modules"* ]]; then                                                                                
                  PKG_NAME=$(echo "$line" | grep -o 'node_modules/[^/"]*' | sed 's/node_modules\///' | head -n 1)                       
                  SIZE=$(echo "$line" | grep -o '"renderedLength":[0-9]*' | cut -d':' -f2)                                              
                  if [ ! -z "$SIZE" ] && [ $SIZE -gt 5120 ]; then                                                                       
                    KB_SIZE=$((SIZE/1024))                                                                                              
                    printf "%-20s %6d KB\n" "$PKG_NAME" "$KB_SIZE"                                                                      
                  fi                                                                                                                    
                fi                                                                                                                      
              done < temp_modules.txt | sort -k2 -nr | head -n 10                                                                       

                                                                                                                          
              echo "\`\`\`"                                                                                               
              echo "EOF"                                                                                                  
            } >> $GITHUB_OUTPUT                                                                                           
                                                                                                                          
            # Clean up                                                                                                    
            rm temp_modules.txt                                                                                           
                                                                                                                          
            # Show final output for debugging                                                                             
            echo "Final output:"                                                                                          
            cat $GITHUB_OUTPUT                                                                                            
          else                                                                                                            
            echo "Stats file not found at dist/stats.html"                                                                
            exit 1                                                                                                        
          fi                                                                                                              
                                                                                                                           
      - name: Read and post stats                                                                                         
        if: success()                                                                                                     
        uses: mshick/add-pr-comment@v2                                                                                    
        with:                                                                                                             
          message: |                                                                                                      
            ## 📊 Bundle Size Analysis                                                                                    
                                                                                                                          
            ```                                                                                                           
            ${{ steps.stats-extract.outputs.stats }}                                                                      
            ```                                                                                                           
                                                                                                                          
            <details>                                                                                                     
            <summary>What is this?</summary>                                                                              
            This is an automated bundle size report generated during the build process. It shows the size of each chunk in the bundle.                                                                                                               
            </details>                                                                                                    
          proxy-url: https://add-pr-comment-proxy-tscircuit.vercel.app/api                                                
          repo-token: ${{ secrets.GITHUB_TOKEN }}                                                                         
          allow-repeats: false                                                                                            
 
