name: Trigger Size Check

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - 'vite.config.ts'
      - 'bun.lockb'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build with stats
        run: |
          VITE_BUNDLE_ANALYZE=true bun run build --mode production

      - name: Save stats as artifact                                                                                      
        if: success()                                                                                                     
        uses: actions/upload-artifact@v3                                                                                  
        with:                                                                                                             
          name: bundle-stats                                                                                              
          path: dist/stats.html                                                                                           

      - name: Extract stats                                                                                               
        id: stats-extract                                                                                                 
        if: success()                                                                                                     
        run: |                                                                                                            
          if [ -f dist/stats.html ]; then                                                                                 
            # Debug: show file content                                                                                    
            echo "Content of stats.html:"                                                                                 
            cat dist/stats.html                                                                                           
                                                                                                                          
            # Try different extraction method                                                                             
            STATS=$(cat dist/stats.html | grep -A 1000 '<pre>' | grep -B 1000 '</pre>' | grep -v '<pre>' | grep -v '</pre>')                                                                                                                 
            # Debug: show extracted content                                                                               
            echo "Extracted content:"                                                                                     
            echo "$STATS"                                                                                                 
                                                                                                                          
            # Escape the content for GitHub Actions output                                                                
            ESCAPED_STATS="${STATS//'%'/'%25'}"                                                                           
            ESCAPED_STATS="${ESCAPED_STATS//$'\n'/'%0A'}"                                                                 
            ESCAPED_STATS="${ESCAPED_STATS//$'\r'/'%0D'}"                                                                 
                                                                                                                          
            # Set output                                                                                                  
            echo "stats=$ESCAPED_STATS" >> $GITHUB_OUTPUT                                                                 
                                                                                                                          
            # Debug: verify output                                                                                        
            echo "Output set to GITHUB_OUTPUT"                                                                            
          else                                                                                                            
            echo "Error: stats.html not found"                                                                            
            ls -la dist/                                                                                                  
            exit 1                                                                                                        
          fi                                                                                                              

                                                                                                                          
      - name: Read and post stats                                                                                         
        if: success()                                                                                                     
        uses: mshick/add-pr-comment@v2                                                                                    
        with:                                                                                                             
          message: |                                                                                                      
            ## 📊 Bundle Size Analysis                                                                                    
                                                                                                                          
            ```                                                                                                           
            ${{ steps.stats-extract.outputs.stats }}                                                                      
            ```                                                                                                           
                                                                                                                          
            <details>                                                                                                     
            <summary>What is this?</summary>                                                                              
            This is an automated bundle size report generated during the build process. It shows the size of each chunk in the bundle.                                                                                                               
            </details>                                                                                                    
          proxy-url: https://add-pr-comment-proxy-tscircuit.vercel.app/api                                                
          repo-token: ${{ secrets.GITHUB_TOKEN }}                                                                         
          allow-repeats: false                                                                                            
 
